<MainWindow>:
    ScreenManager:
        id: screen_manager
        Screen:
            name: 'signin'     # ← Verifica este nombre
            id: scrn_signin
        Screen:
            name: 'operadores'
            id: scrn_operadores
        Screen:
            name: 'inventario'
            id: scrn_inventario
        Screen:
            name: 'fichas'
            id: scrn_fichas
        Screen:
            name: 'admin'
            id: scrn_admin
            