#:import hex kivy.utils.get_color_from_hex

<BotonOscuro@Button>:
	background_normal: ''
	background_color: hex('#393939')

<LabelOscuro@Label>:
	canvas.before:
		Color:
			rgba: hex('#393939')
		Rectangle:
			size: self.size
			pos: self.pos



<AdminRV>:
    SelectableRecycleBoxLayout:
        default_size: None, dp(36)
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: 'vertical'
        multiselect: False
        touch_multiselect: False

<SelectableHistoriaLabel>:
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: hex('#C9F3EF') if self.selected else hex('#F0F0F0')
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        size_hint_y: None
        height: 40
        spacing: 10
        padding: 5

        Label:
            id: _hashtag
            size_hint_x: 0.2
            text: ''
            halign: 'center'
            valign: 'middle'
            text_size: self.size
        	color: (0,0,0,1)
        Label:
            id: _fecha
            size_hint_x: 0.8
            color: (0,0,0,1)

<SelectableUsuarioLabel>:
    # Fondo de selección
    canvas.before:
        Color:
            rgba: hex('#C9F3EFFF') if self.selected else hex('#F0F0F0FF')
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        id: _hashtag
        size_hint_x: .05
        color: (0, 0, 0, 1)

    Label:
        id: _nombre
        size_hint_x: .30
        color: (0, 0, 0, 1)

    Label:
        id: _username
        size_hint_x: .15
        color: (0, 0, 0, 1)

    Label:
        id: _tipo
        size_hint_x: .15
        color: (0, 0, 0, 1)

    Label:
        id: _ci2
        size_hint_x: .15
        color: (0, 0, 0, 1)

    Label:
        id: _cmvb
        size_hint_x: .10
        color: (0, 0, 0, 1)

    Label:
        id: _mpps
        size_hint_x: .10
        color: (0, 0, 0, 1)
<SelectableVentaLabel>:
	canvas.before:
        Color:
            rgba: hex('#C9F3EF') if self.selected else hex('#F0F0F0')
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        id: _hashtag
        size_hint_x: .05
        color: (0,0,0,1)
    Label:
        id: _username
        size_hint_x: .2
        color: (0,0,0,1)
    Label:
        id: _cantidad
        size_hint_x: .2
        color: (0,0,0,1)
    Label:
        id: _total
        size_hint_x: .15
        color: (0,0,0,1)
    Label:
        id: _time
        size_hint_x: .2
        color: (0,0,0,1)
    Label:
        id: _date
        size_hint_x: .2
        color: (0,0,0,1)


<UsuarioPopup>:
    size_hint: .5, .5
    auto_dismiss: False
    title: ''
    BoxLayout:
	    orientation: 'vertical'
	    padding: .05
	    Label:
	    	size_hint_y: .1
	    	id: usuario_info_1
	    Label:
	    	id: no_valid_notif
	    	size_hint_y: .1
	    TextInput: 
			size_hint_y: .2
			id: usuario_username
			multiline: False
			hint_text: 'Username'
			write_tab: False
		TextInput: 
			id: usuario_nombre
			size_hint_y: .2
			multiline: False
			hint_text: 'Nombre'
			write_tab: False
		BoxLayout:
			size_hint_y: .2
			TextInput:
				size_hint_x: .5
				id: usuario_password
				multiline: False
				hint_text: 'Password'
				password: True
				write_tab: False
			ToggleButton: 
				size_hint_x: .25
				id: admin_tipo
				text: 'Admin'
				group: 'usuario_tipo'
			ToggleButton: 
				size_hint_x: .25
				id: trabajador_tipo
				text: 'Trabajador'
				group: 'usuario_tipo'
		BoxLayout:
			size_hint_y: .2
		    Button:
		    	text: 'Aceptar'
		    	on_release: root.verificar(usuario_username.text, usuario_nombre.text, usuario_password.text, admin_tipo.state, trabajador_tipo.state)
		    Button:
		        text: 'Salir sin hacer cambios'
		        on_press: root.dismiss()




<VistaUsuarios>:
    name: 'Usu'
    BoxLayout:
        BoxLayout:
            padding: .5
            orientation: 'vertical'
            BoxLayout:
                size_hint_y: .05
                spacing: .5
                LabelOscuro:
                    text: '#'
                    size_hint_x: .05
                LabelOscuro:
                    text: 'Nombre'
                    size_hint_x: .30
                LabelOscuro:
                    text: 'Username'
                    size_hint_x: .15
                LabelOscuro:
                    text: 'Tipo'
                    size_hint_x: .15
                LabelOscuro:
                    text: 'C.I'
                    size_hint_x: .15
                LabelOscuro:
                    text: 'CMVB'
                    size_hint_x: .10
                LabelOscuro:
                    text: 'MPPS'
                    size_hint_x: .10

            AdminRV:
                id: rv_usuarios
                size_hint_y: .89
                viewclass: 'SelectableUsuarioLabel'
        BoxLayout:
            spacing: .5
            size_hint_x: .2
            orientation: 'vertical'
            padding: .5
            BotonOscuro:
                text: 'Agregar Usuario'
                on_release: root.agregar_usuario()
            BotonOscuro:
                text: 'Modificar Usuario'
                on_release: root.modificar_usuario()
            BotonOscuro:
                text: 'Eliminar Usuario'
                on_release: root.eliminar_usuario()
            BotonOscuro:
                text: 'Agregar Veterinario'
                on_release: root.agregar_vet()
            BotonOscuro:
                text: 'Modificar Veterinario'
                on_release: root.modificar_vet()
            BotonOscuro:
                text: 'Eliminar Veterinario'
                on_release: root.eliminar_vet()


<CustomDropDown>:
	canvas.before:
		Color:
			rgba: hex('#393939')
		Rectangle:
			size: self.size
			pos: self.pos
    Button:
        text: 'Consultas'
        size_hint_y: None
        height: 44
        on_release: root.vista(self.text)
    Button:
        text: 'Inventario'
        size_hint_y: None
        height: 44
        on_release: root.vista(self.text)
    Button:
        text: 'Pacientes'
        size_hint_y: None
        height: 44
        on_release: root.vista(self.text)
    Button:
        text: 'Operador'
        size_hint_y: None
        height: 44
        on_release: root.vista(self.text)
	Button:
        text: 'Usuarios'
        size_hint_y: None
        height: 44
        on_release: root.vista(self.text) 

<AdminWindow>:
	id: main_win
	orientation: 'vertical'
	canvas.before:
		Color:
			rgba: hex('#159F9A')
		Rectangle:
			size: self.size
			pos: self.pos

	BoxLayout:
		orientation: 'vertical'
		size_hint_y: .1
		BoxLayout:
			padding: .1
			spacing: .2
			BotonOscuro:
				id: cambiar_vista
				size_hint_x: .2
				text: 'Cambiar Vista'
				on_release: root.cambiar_vista()
			Label:
				id: mostrat_usuario
				size_hint_x: .2
				color: hex('#000000')
			Label:
				size_hint_x: .2
			Label:
				id: notification
				size_hint_x: .2
			BotonOscuro:
				id: boton_signout
				size_hint_x: .2
				text: 'Salir de Cuenta'
				on_release: root.salir()

	ScreenManager:
        id: vista_manager
		canvas.before:
			Color:
				rgba: hex('#FFFFFF')
			Rectangle:
				size: self.size
				pos: self.pos
		VistaPacientes:
		    id: vista_pacientes
		VistaInventario:
		    id: vista_inventario
        VistaConsultas:
		    id: vista_consultas
		VistaUsuarios:
			id: vista_usuarios
		VistaOperador:
			id: vista_operador



    BoxLayout:
    	size_hint_y:.05


<VistaConsultas>:
    name: 'Consultas'
    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            padding: 10
            spacing: 8
            size_hint_y: None
            height: self.minimum_height
            Label:
                id: notificacion  # ← ¡ES IMPORTANTE QUE ESTE ID EXISTA!
                text: ''
                color: (1, 0, 0, 1)
                size_hint_y: None
                height: 30

            # Título: DATOS DEL PROPIETARIO
            LabelOscuro:
                text: 'DATOS DEL PROPIETARIO'
                size_hint_y: None
                height: 30
                color: (1, 1, 1, 1)

            # Campos en fila horizontal
            BoxLayout:
                size_hint_y: None
                height: 60
                spacing: 10
                orientation: 'horizontal'

                # Propietario
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Propietario:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: propietario
                        multiline: False

                # C.I.
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'C.I.:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: ci
                        multiline: False
						input_filter: 'int'  

                # Teléfono
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Teléfono:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: telefono
                        multiline: False
						input_filter: 'int'  

                # Dirección
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Dirección:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: direccion
                        multiline: False

            # Motivo de consulta
            BoxLayout:
                size_hint_y: None
                height: 30
                spacing: 10
                Label:
                    text: 'Motivo de consulta:'
                    color: (0, 0, 0, 1)
                    size_hint_x: 0.3
                TextInput:
                    id: motivo_consulta
                    multiline: False
                    size_hint_x: 0.7

            # Título: DATOS DEL ANIMAL
            LabelOscuro:
                text: 'DATOS DEL ANIMAL'
                size_hint_y: None
                height: 30
                color: (1, 1, 1, 1)

            # Datos del Animal (en filas horizontales)
            BoxLayout:
                size_hint_y: None
                height: 60
                spacing: 10
                orientation: 'horizontal'

                # Nombre del animal
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Nombre del animal:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: nombre_animal
                        multiline: False

                # Especie
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Especie:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: especie
                        multiline: False

                # Raza
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Raza:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: raza
                        multiline: False

                # Sexo
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Sexo:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: sexo
                        multiline: False

            BoxLayout:
                size_hint_y: None
                height: 60
                spacing: 10

                # Edad
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Edad:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: edad
                        multiline: False

                # Pelaje
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Pelaje:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: pelaje
                        multiline: False

                # C.C.
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'C.C.:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: cc
                        multiline: False

                # enfermedad
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Enfermedad:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: enfermedad
                        multiline: False

            BoxLayout:
                size_hint_y: None
                height: 60
                spacing: 10

                # Tratamiento
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.25
                    Label:
                        text: 'Tratamiento:'
                        color: (0, 0, 0, 1)
                    TextInput:
                        id: tratamiento
                        multiline: False

            # Botones
            BoxLayout:
                size_hint_y: None
                height: 40
                spacing: 15
                BotonOscuro:
                    text: 'Siguiente'
                    on_release: root.siguiente()
                BotonOscuro:
                    text: 'Limpiar'
                    on_release: root.limpiar()

<SelectablePacienteLabel>:
    canvas.before:
        Color:
            rgba: hex('#C9F3EF') if self.selected else hex('#F0F0F0')
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        id: _hashtag
        size_hint_x: .05
        color: (0,0,0,1)
    Label:
        id: _nombre_propietario
        size_hint_x: .35
        color: (0,0,0,1)
    Label:
        id: _ci
        size_hint_x: .2
        color: (0,0,0,1)
    Label:
        id: _nombre_mascota
        size_hint_x: .25
        color: (0,0,0,1)
    Label:
        id: _telefono
        size_hint_x: .15
        color: (0,0,0,1)

<SelectableExamenLabel>:
    canvas.before:
        Color:
            rgba: hex('#C9F3EF') if self.selected else hex('#F0F0F0')
        Rectangle:
            size: self.size
            pos: self.pos
    Label:
        id: _hashtag
        size_hint_x: .1
        color: (0,0,0,1)
    Label:
        id: _fecha
        size_hint_x: .2
        color: (0,0,0,1)
    Label:
        id: _peso
        size_hint_x: .10
        color: (0,0,0,1)
    Label:
        id: _anamnesis
        size_hint_x: .25
        color: (0,0,0,1)
    Label:
        id: _diagnostico
        size_hint_x: .35
        color: (0,0,0,1)


<ExamenesClinicosPopup>:
    size_hint: .9, .8
    auto_dismiss: False
    title: 'Exámenes Clínicos'
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10
        
        # Encabezados
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            LabelOscuro:
                text: '#'
                size_hint_x: .1
            LabelOscuro:
                text: 'Fecha'
                size_hint_x: .2
            LabelOscuro:
                text: 'Peso'
                size_hint_x: .10
            LabelOscuro:
                text: 'anamnesis'
                size_hint_x: .25
            LabelOscuro:
                text: 'Diagnóstico'
                size_hint_x: .35
        
        # Lista de exámenes
        AdminRV:
            id: rv_examenes
            viewclass: 'SelectableExamenLabel'
        
        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            
            Button:
                text: ' Nuevo Examen'
                background_color: (0.2, 0.7, 0.3, 1)
                on_release: root.nuevo_examen()
            
            Button:
                text: ' Ver Detalle'
                background_color: (0.3, 0.5, 0.8, 1)
                on_release: root.ver_detalle_examen()
            
            Button:
                text: ' Eliminar'
                background_color: (0.9, 0.3, 0.3, 1)
                on_release: root.eliminar_examen()
            
            Button:
                text: ' Cerrar'
                background_color: (0.6, 0.6, 0.6, 1)
                on_release: root.dismiss()


<HistoriasMedicasPopup>:
    size_hint: .9, .8
    auto_dismiss: False
    title: 'Historias Médicas'

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        Label:
            id: mensaje_estado
            size_hint_y: None
            height: 30
            text: ""
            color: 0, 0, 0, 1
            halign: 'center'
            text_size: self.size

        BoxLayout:
            orientation: 'vertical'
            size_hint_y: 0.7
            spacing: 5

            LabelOscuro:
                text: 'HISTORIAS DERMATOLÓGICAS'
                size_hint_y: None
                height: 30

            BoxLayout:
                size_hint_y: None
                height: 30
                spacing: 5
                LabelOscuro:
                    text: 'N°'
                    size_hint_x: 0.2
                LabelOscuro:
                    text: 'Fecha'
                    size_hint_x: 0.8

            AdminRV:
                id: rv_historias_dermatologicas
                viewclass: 'SelectableHistoriaLabel'

             

        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10

            BotonOscuro:
                text: ' Nueva'
                background_color: (0.2, 0.7, 0.3, 1)
                on_release: root.nueva_historia_der()

            BotonOscuro:
                text: ' Detalle'
                background_color: (0.3, 0.5, 0.8, 1)
                on_release: root.editar_historia_dermatologica()

            BotonOscuro:
                text: ' Eliminar'
                background_color: (0.9, 0.3, 0.3, 1)
                on_release: root.eliminar_historia_dermatologica()

            BotonOscuro:
                text: ' Cerrar'
                background_color: (0.6, 0.6, 0.6, 1)
                on_release: root.dismiss()

     
<RecipesPopup>:
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        # Encabezados
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 5
            LabelOscuro:
                text: '#'
                size_hint_x: .1
            LabelOscuro:
                text: 'Fecha'
                size_hint_x: .2
            LabelOscuro:
                text: 'Doctor'
                size_hint_x: .15
            LabelOscuro:
                text: 'Rp'
                size_hint_x: .15
            LabelOscuro:
                text: 'Ind'
                size_hint_x: .4

        # Lista de recetas
        AdminRV:
            id: rv_examenes
            viewclass: 'SelectableRecipeLabel'

        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10

            Button:
                text: ' Nuevo Recipe'
                background_color: (0.2, 0.7, 0.3, 1)
                on_release: root.nuevo_examen()

            Button:
                text: ' Ver Detalle'
                background_color: (0.3, 0.5, 0.8, 1)
                on_release: root.ver_detalle_recipe()

            Button:
                text: ' Eliminar'
                background_color: (0.9, 0.3, 0.3, 1)
                on_release: root.eliminar_recipe()

            Button:
                text: ' Cerrar'
                background_color: (0.6, 0.6, 0.6, 1)
                on_release: root.dismiss()

<SelectableRecipeLabel>:
    canvas.before:
        Color:
            rgba: (0.8, 0.95, 0.95, 1) if self.selected else (0.95, 0.95, 0.95, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        id: _hashtag
        size_hint_x: .1
        text: ''
        color: (0, 0, 0, 1)
    Label:
        id: _fecha
        size_hint_x: .2
        text: ''
        color: (0, 0, 0, 1)
    Label:
        id: _Doctor
        size_hint_x: .15
        text: ''
        color: (0, 0, 0, 1)
    Label:
        id: _Rp
        size_hint_x: .15
        text: ''
        color: (0, 0, 0, 1)
    Label:
        id: _Ind
        size_hint_x: .4
        text: ''
        color: (0, 0, 0, 1)




<DetalleRecetaPopup>:
    layout: layout
    lbl_veterinario: lbl_veterinario
    lbl_cmvb: lbl_cmvb
    lbl_paciente: lbl_paciente
    rp: rp
    ind: ind
    btn_editar: btn_editar
    btn_guardar: btn_guardar
    btn_imprimir: btn_imprimir

    BoxLayout:
        id: layout
        orientation: 'vertical'
        padding: 20
        spacing: 10

        # Datos del veterinario
        Label:
            id: lbl_veterinario
            text: "Veterinario: N/A"
            bold: True
            size_hint_y: None
            height: 30

        Label:
            id: lbl_cmvb
            text: "CMVB: N/A | MPPS: N/A"
            size_hint_y: None
            height: 30

        Label:
            id: lbl_paciente
            text: "Paciente: N/A"
            bold: True
            size_hint_y: None
            height: 30

        # Campo Rp
        Label:
            text: "Rp (Tratamiento):"
            bold: True
            size_hint_y: None
            height: 30

        TextInput:
            id: rp
            multiline: True
            readonly: True
            background_color: 0.95, 0.95, 0.95, 1

        # Campo Ind
        Label:
            text: "Ind (Indicaciones):"
            bold: True
            size_hint_y: None
            height: 30

        TextInput:
            id: ind
            multiline: True
            readonly: True
            background_color: 0.95, 0.95, 0.95, 1

        # Botones
        BoxLayout:
            orientation: 'vertical'
            padding: 20
            spacing: 10

            Button:
                id: btn_editar
                text: "Editar Receta"
                background_color: 0.3, 0.5, 0.8, 1
                size_hint_y: None
                height: 50
                on_release: root.toggle_edicion()

            Button:
                id: btn_guardar
                text: "Guardar Cambios"
                background_color: 0.2, 0.7, 0.3, 1
                size_hint_y: None
                height: 50
                opacity: 0
                disabled: True
                on_release: root.guardar_cambios()

            Button:
                id: btn_imprimir
                text: " Imprimir Receta"
                background_color: 0.8, 0.5, 0.2, 1
                size_hint_y: None
                height: 50
                on_release: root.imprimir_receta()
            Button:
                text: "Cancelar"
                background_color: 0.8, 0.5, 0.2, 1
                size_hint_y: None
                height: 50
                on_release: root.dismiss()

<NuevoExamenPopup>:
    size_hint: .9, .95
    auto_dismiss: False
    title: 'Nuevo Examen Clínico'

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        # Mensaje de estado
        Label:
            id: mensaje_estado
            size_hint_y: None
            height: 30
            text: ''
            color: 1, 1, 1, 1

        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10

                # Información General
                LabelOscuro:
                    text: 'Control de Torno y Soldadura'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 25
                    bold: True

                # Fecha (automática, solo lectura)
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Fecha:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_fecha
                        text: ''  # Se llenará desde Python con la fecha actual
                        readonly: True
                        size_hint_x: 0.7

                # Recibido por
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Recibido por:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_recibido_por
                        size_hint_x: 0.7

                # Cliente
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Cliente:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_cliente
                        size_hint_x: 0.7

                # Teléfono
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Teléfono:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_telefono
                        size_hint_x: 0.7

                # Dirección
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Dirección:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_direccion
                        size_hint_x: 0.7

                # RIF/C.I
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'RIF/C.I.:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_rif_ci
                        size_hint_x: 0.7

                # Partes Recibidas
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Partes Recibidas:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_partes_recibidas
                        multiline: True
                        size_hint_x: 0.7

                # Costo Trabajo
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Costo Trabajo:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_costo_trabajo
                        input_filter: 'float'
                        size_hint_x: 0.7

                # Abono/Anticipo
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Abono/Anticipo:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_abono
                        input_filter: 'float'
                        size_hint_x: 0.7

                # Trabajos a realizar
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Trabajos a realizar:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_trabajos_realizar
                        multiline: True
                        size_hint_x: 0.7

                # Detalles del Equipo/Materiales
                LabelOscuro:
                    text: 'DETALLES DEL EQUIPO/MATERIALES'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True

                # Tabla para detalles (5 columnas x 11 filas)
                GridLayout:
                    cols: 5
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 30
                    padding: 10
                    spacing: 10

                    # Encabezados
                    Label:
                        text: 'ITEM'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'DESCRIPCIÓN'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANTIDAD'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'MODELO'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'SERIAL'
                        color: 1, 1, 1, 1

                    # Filas dinámicas (11 filas)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_1
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_1
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_1
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_1
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_1
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_2
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_2
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_2
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_2
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_2
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_3
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_3
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_3
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_3
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_3
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_4
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_4
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_4
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_4
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_4
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_5
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_5
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_5
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_5
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_5
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_6
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_6
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_6
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_6
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_6
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_7
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_7
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_7
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_7
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_7
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_8
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_8
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_8
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_8
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_8
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_9
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_9
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_9
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_9
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_9
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_10
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_10
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_10
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_10
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_10
                            size_hint_x: 0.1

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: item_11
                            size_hint_x: 0.2
                        TextInput:
                            id: descripcion_11
                            size_hint_x: 0.4
                        TextInput:
                            id: cantidad_11
                            size_hint_x: 0.2
                        TextInput:
                            id: modelo_11
                            size_hint_x: 0.1
                        TextInput:
                            id: serial_11
                            size_hint_x: 0.1

                # Total Materiales
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'TOTAL MATERIALES:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: total_materiales
                        size_hint_x: 0.7

        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 20
            BotonOscuro:
                text: 'Guardar'
                on_release: root.guardar_examen()
            BotonOscuro:
                text: 'Cancelar'
                on_release: root.dismiss()

<DetalleExamenPopup>:
    size_hint: .9, .95
    auto_dismiss: False
    title: 'Detalle del Examen Clínico'
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10
        
        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                
                # Anamnesis y Antecedentes
                LabelOscuro:
                    text: 'ANAMNESIS Y ANTECEDENTES'
                    size_hint_y: None
                    height: 30
                
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Desparasitaciones:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_desparasitaciones
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
                        color: 1, 1, 1, 1
                
                    Label:
                        text: 'Vacunas:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_vacuna
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
                        color: 1, 1, 1, 1
                
                    Label:
                        text: 'Alimentación:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_alimentacion
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
                        color: 1, 1, 1, 1


                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Anamnesis:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_anamnesis
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
                        color: 1, 1, 1, 1
                




                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Peso (kg):'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_peso
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Temperatura aaaa (°C):'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_temperatura
                        size_hint_x: 0.3
						readonly: True
                        text_size: self.size
                        halign: 'left'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'F.C:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_fc
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                    Label:
                        text: 'F.R:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_fr
                        size_hint_x: 0.3
                        text_size: self.size
						readonly: True
                        halign: 'left'
                        color: 1, 1, 1, 1
                # Examen Físico
                LabelOscuro:
                    text: 'EXAMEN FÍSICO'
                    size_hint_y: None
                    height: 30
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'P. Femoral:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_p_femoral
                        size_hint_x: 0.3
                        text_size: self.size
						readonly: True
                        halign: 'left'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Yugular:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_yugular
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'T.P.G:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_tpg
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                    Label:
                        text: 'PS:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_ps
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'PD:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_pd
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                    Label:
                        text: 'PAM:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_pam
                        size_hint_x: 0.3
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Mucosas:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_mucosas
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Ganglios:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_ganglios
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Palp. Abdominal:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_palp_abdominal
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Patrón Lesión:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_patron_lesion
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Genitales:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_genitales
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1
                # Diagnósticos y Tratamientos
                LabelOscuro:
                    text: 'DIAGNÓSTICOS Y TRATAMIENTOS'
                    size_hint_y: None
                    height: 30
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Procedimiento Diagnóstico:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_procedimiento_diagnos
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        valign: 'top'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Pruebas Complementarias:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_pruebas_comple
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        valign: 'top'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Diagnóstico Diferencial:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_diag_diferencial
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        valign: 'top'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Diagnóstico Definitivo:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_diag_definitivo
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Tratamiento Aplicado:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_tratamiento_apli
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        valign: 'top'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 60
                    spacing: 10
                    Label:
                        text: 'Tratamiento Indicado:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_tratamiento_indi
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
                        valign: 'top'
						readonly: True
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Próxima Consulta:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_proxi_consulta
                        size_hint_x: 0.7
                        text_size: self.size
						readonly: True
                        halign: 'left'
                        color: 1, 1, 1, 1
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Fecha del Examen:'
                        size_hint_x: 0.3
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_examen_fecha
                        size_hint_x: 0.7
                        text_size: self.size
                        halign: 'left'
						readonly: True
                        color: 1, 1, 1, 1


                #
                Label:
                    text: "EXAMENES DE LABORATORIO"
                    size_hint_y: None
                    height: dp(30)
                    bold: True
                    color: 1, 1, 1, 1

                GridLayout:
                    cols: 10
                    rows: 8
                    size_hint_y: None
                    height: 8 * 40  # 8 filas de 40dp de alto
                    spacing: 2, 2
                    padding: 0


                    # Fila 1
                    Label:
                        text: 'Laboratorios'
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: ''
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: 'HEMATOLOGÍA'
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: ''
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: ''
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: ''
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: 'PERFIL RENAL'
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: ''
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: 'PERFIL HEPÁTICO'
                        color: 1, 1, 1, 1
                        background_color: 0.2, 0.2, 0.2, 1
                    Label:
                        text: 'OTRAS'
                        color: 1, 1, 1, 1
                        background_color: 1, 1, 1, 1

                    # Fila 2
                    TextInput:
                        id: detalle_lab
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Hb"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_hb
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Eosi"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_eosi
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "Urea"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_urea
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "ALT"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_alt
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    TextInput:
                        id: detalle_otras_20
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
               
                    # Fila 3

                    Label:
                        text: ""
                        color: (0, 0, 0, 1)
                    Label:
                        text: "Hto"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_hto
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Plaq"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_plaq
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Creat"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_creat
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "AST"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_ast
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    TextInput:
                        id: detalle_otras_30
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                   # Fila 4

                    Label:
                        text: ""
                        color: (0, 0, 0, 1)
                    Label:
                        text: "Leuc"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_leuc
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "VCM"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_vcm
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Bun"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_bun
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "FA"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_fa
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                    TextInput:
                        id: detalle_otras_40
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)


                   # Fila 5

                    Label:
                        text: ""
                        color: (0, 0, 0, 1)
                    Label:
                        text: "Neut"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_neut
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "HCM"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_hcm
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "PT"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_pt
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "BT"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_bt
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                    TextInput:
                        id: detalle_otras_50
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)



                   # Fila 6

                    Label:
                        text: ""
                        color: (0, 0, 0, 1)
                    Label:
                        text: "LINF"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_lint
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "CHCM"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_chcm
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Alb"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_alb
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "BI"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_bi
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                    TextInput:
                        id: detalle_otras_60
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                   # Fila 7

                    Label:
                        text: ""
                        color: (0, 0, 0, 1)
                    Label:
                        text: "Mon"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_mon
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Descar"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_descar
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    Label:
                        text: "Glo"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_glo
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                    
                    Label:
                        text: "BD"
                        color: 1, 1, 1, 1
                    TextInput:
                        id: detalle_bd
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

                    TextInput:
                        id: detalle_otras_70
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)

        #
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            
            Button:
                id: btn_editar
                text: 'Editar Examen'
                on_release: root.toggle_edicion()
            
            Button:
                id: btn_guardar
                text: 'Guardar Cambios'
                opacity: 0
                disabled: True
                on_release: root.guardar_cambios()
            
            Button:
                text: 'Cerrar'
                on_release: root.dismiss()

<DetallePacientePopup>:
    size_hint: .8, .9
    auto_dismiss: False
    title: 'Detalle del Paciente'
    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10
        
        # Mensaje de estado
        Label:
            id: mensaje_estado
            size_hint_y: None
            height: 30
            text: ''
            color: (0, 1, 0, 1)
        
        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10
                
                LabelOscuro:
                    text: 'DATOS DEL PROPIETARIO'
                    size_hint_y: None
                    height: 30
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Propietario:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_propietario
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'C.I.:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_ci
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Teléfono:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_telefono
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Dirección:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_direccion
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Motivo de consulta:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_motivo
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                LabelOscuro:
                    text: 'DATOS DEL ANIMAL'
                    size_hint_y: None
                    height: 30
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Nombre mascota:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_nombre_mascota
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Especie:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_especie
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Raza:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_raza
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Sexo:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_sexo
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Edad:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_edad
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Pelaje:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_pelaje
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'C.C.:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_cc
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Enfermedad:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_enfermedad
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
                
                BoxLayout:
                    size_hint_y: None
                    height: 30
                    Label:
                        text: 'Tratamiento:'
                        size_hint_x: 0.3
                    TextInput:
                        id: detalle_tratamiento
                        size_hint_x: 0.7
                        multiline: False
                        readonly: True
                        background_color: (0.9, 0.9, 0.9, 1)
    
		BoxLayout:
			size_hint_y: None
			height: 50
			spacing: 10
			BotonOscuro:
				id: btn_editar
				text: 'Editar'
				on_release: root.toggle_edicion()
			BotonOscuro:
				id: btn_guardar
				text: 'Guardar'
				opacity: 0
				disabled: True
				on_release: root.guardar_cambios()
			BotonOscuro:
				text: 'Exámenes Clínicos'
				on_release: root.mostrar_examenes_clinicos()
            BotonOscuro:
				text: 'Historias'
				on_release: root.mostrar_historias_medicas()
			BotonOscuro:
				text: 'Recipes'
				on_release: root.eliminar_paciente()
			BotonOscuro:
				text: 'Cerrar'
				on_release: root.dismiss()

<VistaPacientes>:
    name: 'Pacientes'
    BoxLayout:
        orientation: 'vertical'
        
        # Sección de filtros
        BoxLayout:
            size_hint_y: .1
            spacing: 5
            padding: 5
            
            LabelOscuro:
                text: 'Filtros:'
                size_hint_x: .15
            
            TextInput:
                id: filtro_propietario
                hint_text: 'Buscar por propietario'
                multiline: False
                size_hint_x: .25
                on_text_validate: root.filtrar_pacientes()
            
            TextInput:
                id: filtro_ci
                hint_text: 'Buscar por C.I.'
                multiline: False
                size_hint_x: .2
                on_text_validate: root.filtrar_pacientes()
            
            TextInput:
                id: filtro_mascota
                hint_text: 'Buscar por mascota'
                multiline: False
                size_hint_x: .25
                on_text_validate: root.filtrar_pacientes()
            
            BotonOscuro:
                text: 'Filtrar'
                size_hint_x: .1
                on_release: root.filtrar_pacientes()
            
            BotonOscuro:
                text: 'Limpiar'
                size_hint_x: .05
                on_release: root.limpiar_filtros()
        
        BoxLayout:
            # Lista de pacientes
            BoxLayout:
                padding: .5
                orientation: 'vertical'
                
                # Encabezados
                BoxLayout:
                    size_hint_y: .05
                    spacing: .5
                    LabelOscuro:
                        text: '#'
                        size_hint_x: .05
                    LabelOscuro:
                        text: 'Propietario'
                        size_hint_x: .35
                    LabelOscuro:
                        text: 'C.I.'
                        size_hint_x: .2
                    LabelOscuro:
                        text: 'Mascota'
                        size_hint_x: .25
                    LabelOscuro:
                        text: 'Teléfono'
                        size_hint_x: .15
                
                # Lista
                AdminRV:
                    id: rv_pacientes
                    size_hint_y: .89
                    viewclass: 'SelectablePacienteLabel'
            
            # Botones laterales
            BoxLayout:
                spacing: .5
                size_hint_x: .2
                orientation: 'vertical'
                padding: .5
                
                BotonOscuro:
                    text: ' Ver Detalle'
                    on_release: root.mostrar_detalle_paciente()
                
                BotonOscuro:
                    text: ' Eliminar Paciente'
                    background_color: (0.9, 0.3, 0.3, 1)
                    on_release: root.eliminar_paciente()  # ✅ Conectado al nuevo método
                
                BotonOscuro:
                    text: ' Actualizar Lista'

                    on_release: root.cargar_pacientes()

<FichaRectificadora>:
    size_hint: .9, .95
    auto_dismiss: False
    title: 'Recepción de Partes'

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        # Mensaje de estado
        Label:
            id: mensaje_estado
            size_hint_y: None
            height: 30
            text: ''
            color: 1, 1, 1, 1

        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10

                # Información del Cliente
                LabelOscuro:
                    text: 'DATOS CLIENTE'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'RIF:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1

                    Spinner:
                        id: tipo_rif
                        text: 'V-'
                        values: ['V-', 'E-', 'P-', 'J-', 'G-', 'R-']
                        size_hint_x: 0.05
                    TextInput:
                        id: nuevo_rif
                        size_hint_x: 0.2
                    Label:
                        text: 'CLIENTE:'
                        size_hint_x: 0.05
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_cliente
                        size_hint_x: 0.4
                    Label:
                        text: 'Fecha:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nueva_fecha
                        text: ''  # Se llenará desde Python con la fecha actual
                        readonly: True
                        size_hint_x: 0.1

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'TELEFONO:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_telefono
                        size_hint_x: 0.2
                    Label:
                        text: 'DIRECCIÓN:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nueva_direccion
                        size_hint_x: 0.4
                    Button:
                        text: 'Guardar Nuevo Cliente'
                        size_hint_x: 0.2
                        on_release: root.guardar_nuevo_cliente()


                # Mano de Obra a Asignar al Trabajo
                LabelOscuro:
                    text: 'MOTOR'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True


                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Motor'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    Spinner:
                        id: tipo_motor
                        text: 'Seleccionar'
                        values: ['Gasolina', 'Diésel', 'Híbrido']
                        size_hint_x: 0.3
                    Label:
                        text: 'SERIAL DE MOTOR:'
                        size_hint_x: 0.2
                        color: 1, 1, 1, 1
                    TextInput:
                        id: serial_motor
                        size_hint_x: 0.4

                # Partes Recibidas
                LabelOscuro:
                    text: 'PARTES RECIBIDAS'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True

                GridLayout:
                    cols: 12
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 30
                    padding: 10
                    spacing: 10

                    # Encabezados
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Partes Recibidas'
                        color: 1, 1, 1, 1

                    # Fila 1
                    TextInput:
                        id: cantidad_grid_1
                        input_filter: 'float'
                    Label:
                        id: ciguenal
                        text: 'Cigueñal'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_2
                        input_filter: 'float'
                    Label:
                        id: bujias
                        text: 'Bujias'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_3
                        input_filter: 'float'
                    Label:
                        id: polea
                        text: 'Polea'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_4
                        input_filter: 'float'
                    Label:
                        id: Multiple
                        text: 'multiple'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_5
                        input_filter: 'float'
                    Label:
                        id: bloque
                        text: 'Bloque'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_6
                        input_filter: 'float'
                    Label:
                        id: bodis
                        text: 'Bodis'
                        color: 1, 1, 1, 1

                    #Fila 2

                    TextInput:
                        id: cantidad_grid_7
                        input_filter: 'float'
                    Label:
                        id: volante
                        text: 'Volante'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_8
                        input_filter: 'float'
                    Label:
                        id: Carter
                        text: 'carter'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_9
                        input_filter: 'float'
                    Label:
                        id: tapas_de_bancada
                        text: 'Tapas de Bancada'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_10
                        input_filter: 'float'
                    Label:
                        id: puntas
                        text: 'puntas'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_11
                        input_filter: 'float'
                    Label:
                        id: engranajes
                        text: 'Engranajes'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_12
                        input_filter: 'float'
                    Label:
                        id: camisas
                        text: 'Camisas'
                        color: 1, 1, 1, 1

                    #Fila 3

                    TextInput:
                        id: cantidad_grid_13
                        input_filter: 'float'
                    Label:
                        id: arbol_de_leva
                        text: 'Árbol de Leva'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_14
                        input_filter: 'float'
                    Label:
                        id: esparragos
                        text: 'Esparragos'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_15
                        input_filter: 'float'
                    Label:
                        id: balancines
                        text: 'Balancines'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_16
                        input_filter: 'float'
                    Label:
                        id: camaras
                        text: 'Cámaras'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_17
                        input_filter: 'float'
                    Label:
                        id: tapa_valvulas
                        text: 'Tapa Válvulas'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_18
                        input_filter: 'float'
                    Label:
                        id: toma_de_agua
                        text: 'Toma de agua'
                        color: 1, 1, 1, 1


                    #Fila 4

                    TextInput:
                        id: cantidad_grid_19
                        input_filter: 'float'
                    Label:
                        id: valvulas_adm
                        text: 'Válvulas Adm.'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_20
                        input_filter: 'float'
                    Label:
                        id: bielas
                        text: 'Bielas'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_21
                        input_filter: 'float'
                    Label:
                        id: chambers
                        text: 'Chambers'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_22
                        input_filter: 'float'
                    Label:
                        id: valvulas_adm
                        text: 'Válvulas Esc.'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_23
                        input_filter: 'float'
                    Label:
                        id: tapas_de_vielas
                        text: 'Tapas de Bielas'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_24
                        input_filter: 'float'
                    Label:
                        id: bomba_de_aceite
                        text: 'Bomba de Aceite'
                        color: 1, 1, 1, 1

                   #Fila 5

                    TextInput:
                        id: cantidad_grid_25
                        input_filter: 'float'
                    Label:
                        id: resortes
                        text: 'Resortes'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_26
                        input_filter: 'float'
                    Label:
                        id: camarin
                        text: 'camarin'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_27
                        input_filter: 'float'
                    Label:
                        id: toma_de_agua
                        text: 'Toma de Agua'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_28
                        input_filter: 'float'
                    Label:
                        id: cuñadas
                        text: 'Cuñadas'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_29
                        input_filter: 'float'
                    Label:
                        id: pasador
                        text: 'Pasador'
                        color: 1, 1, 1, 1
                    TextInput:
                        id: cantidad_grid_30
                        input_filter: 'float'
                    Label:
                        id: base_de_agua
                        text: 'Base de Agua'
                        color: 1, 1, 1, 1




                # Botones adicionales
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Button:
                        text: 'Incluir Repuestos'
                        on_release: root.incluir_repuestos()
                    Button:
                        text: 'Incluir Servicios Especiales'
                        on_release: root.incluir_servicios_especiales()
                    Button:
                        text: 'Imprimir Ficha Registrada'
                        on_release: root.imprimir_ficha()



                BoxLayout:

                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Mano de Obra:'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.15
                    TextInput:
                        id: mano_de_obra
                        readonly: True
                        size_hint_x: 0.35
                    Label:
                        text: 'I.V.A (16%):'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.15
                    TextInput:
                        id: iva
                        readonly: True
                        size_hint_x: 0.35
                    Label:
                        text: 'TOTAL+IVA:'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.15
                    TextInput:
                        id: total_iva
                        readonly: True
                        size_hint_x: 0.35






        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 20
            BotonOscuro:
                text: 'Guardar'
                on_release: root.guardar_recepcion()
            BotonOscuro:
                text: 'Cancelar'
                on_release: root.dismiss()


<SelectableOperadorLabel>:
    canvas.before:
        Color:
            rgba: hex('#E8F5E8') if self.selected else hex('#F0F0F0')
        Rectangle:
            size: self.size
            pos: self.pos
    # No uses un BoxLayout anidado
    # Los widgets deben estar directamente en el contenedor
    _hashtag: _hashtag
    _nombre: _nombre
    _porcentaje: _porcentaje
    _tasa: _tasa

    Label:
        id: _hashtag
        size_hint_x: .05
        text: ''
        color: (0,0,0,1)
    Label:
        id: _nombre
        size_hint_x: .25
        text: ''
        color: (0,0,0,1)
    Label:
        id: _porcentaje
        size_hint_x: .15
        text: ''
        color: (0,0,0,1)
    Label:
        id: _tasa
        size_hint_x: .15
        text: ''
        color: (0,0,0,1)

<VistaOperador>:
    name: 'Operador'
    BoxLayout:
        orientation: 'vertical'
        padding: 10
        spacing: 10
        size_hint_y: 1  # Ocupa todo el alto del Screen
        height: self.minimum_height  # Ajusta la altura al contenido (opcional si usas ScrollView)

        # Título
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            LabelOscuro:
                text: 'TABLA DE OPERADORES'
                size_hint_x: 1  # Ocupa todo el ancho
                font_size: '18sp'
                bold: True
                halign: 'center'
                valign: 'middle'

        # Barra de búsqueda
        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            Label:
                text: 'Buscar:'
                size_hint_x: None
                width: 80
                color: (0,0,0,1)
            TextInput:
                id: filtro_busqueda
                multiline: False
                hint_text: 'Nombre o código'
                on_text: root.filtrar_agenda(self.text)

        # Encabezados de tabla
        BoxLayout:
            size_hint_y: None
            height: 30
            spacing: 2
            LabelOscuro:
                text: 'CODIGO'
                size_hint_x: .05
                bold: True
                color: (1,1,1,1)
            LabelOscuro:
                text: 'NOMBRE'
                size_hint_x: .25
                bold: True
                color: (1,1,1,1)
            LabelOscuro:
                text: 'Porcentaje %'
                size_hint_x: .15
                bold: True
                color: (1,1,1,1)
            LabelOscuro:
                text: 'TASA'
                size_hint_x: .15
                bold: True
                color: (1,1,1,1)

        # Lista de operadores (con scroll si hay muchas filas)
        AdminRV:
            id: rv_operador
            viewclass: 'SelectableOperadorLabel'
            size_hint_y: 1  # ¡Importante! Usa todo el espacio vertical restante
            scroll_type: ['bars']
            scroll_wheel_distance: 100

        # Botones al final
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 10
            Button:
                text: 'Editar'
                size_hint_x: 0.2
                on_release: root.editar_operador()
            Button:
                text: 'Eliminar'
                size_hint_x: 0.2
                on_release: root.eliminar_operador()
            Button:
                text: 'Nuevo'
                size_hint_x: 0.2
                on_release: root.nuevo_operador()
            Button:
                text: 'Imprimir'
                size_hint_x: 0.2
                on_release: root.imprimir_ficha()


<RecepcionPartesPopup>:
    size_hint: .9, .95
    auto_dismiss: False
    title: 'Recepción de Partes'

    BoxLayout:
        orientation: 'vertical'
        padding: 20
        spacing: 10

        # Mensaje de estado
        Label:
            id: mensaje_estado
            size_hint_y: None
            height: 30
            text: ''
            color: 1, 1, 1, 1

        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 10

                # Información del Cliente
                LabelOscuro:
                    text: 'DATOS CLIENTE'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'RIF:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1

                    Spinner:
                        id: tipo_rif
                        text: 'V-'
                        values: ['V-', 'E-', 'P-', 'J-', 'G-', 'R-']
                        size_hint_x: 0.05
                    TextInput:
                        id: nuevo_rif
                        size_hint_x: 0.2
                    Label:
                        text: 'CLIENTE:'
                        size_hint_x: 0.05
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_cliente
                        size_hint_x: 0.4
                    Label:
                        text: 'Fecha:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nueva_fecha
                        text: ''  # Se llenará desde Python con la fecha actual
                        readonly: True
                        size_hint_x: 0.1

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'TELEFONO:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nuevo_telefono
                        size_hint_x: 0.2
                    Label:
                        text: 'DIRECCIÓN:'
                        size_hint_x: 0.1
                        color: 1, 1, 1, 1
                    TextInput:
                        id: nueva_direccion
                        size_hint_x: 0.4
                    Button:
                        text: 'Guardar Nuevo Cliente'
                        size_hint_x: 0.2
                        on_release: root.guardar_nuevo_cliente()


                # Mano de Obra a Asignar al Trabajo
                LabelOscuro:
                    text: 'MANO DE OBRA A ASIGNAR AL TRABAJO'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True

                GridLayout:
                    id: grid_mano_obra
                    cols: 6
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 30
                    padding: 10
                    spacing: 10

                    # Encabezados
                    Label:
                        text: 'Mano de Obra (Trabajo)'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Operarios'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Cantidad'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Precio'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'PORC (%)'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'Mano de Obra'
                        color: 1, 1, 1, 1

                    # Filas dinámicas (ejemplo con 3 filas)

                    Spinner:
                        id: mano_obra_1
                        text: 'Seleccionar'
                        values: ['Torno', 'Soldadura', 'Otros']
                        size_hint_x: 0.3
                    TextInput:
                        id: operarios_1
                        input_filter: 'int'
                        size_hint_x: 0.1
                    TextInput:
                        id: cantidad_1
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: precio_1
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: porcentaje_1
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: total_mano_obra_1
                        readonly: True
                        size_hint_x: 0.2

    
                        id: mano_obra_2
                        text: 'Seleccionar'
                        values: ['Torno', 'Soldadura', 'Otros']
                        size_hint_x: 0.3
                    TextInput:
                        id: operarios_2
                        input_filter: 'int'
                        size_hint_x: 0.1
                    TextInput:
                        id: cantidad_2
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: precio_2
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: porcentaje_2
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: total_mano_obra_2
                        readonly: True
                        size_hint_x: 0.2

                    Spinner:
                        id: mano_obra_3
                        text: 'Seleccionar'
                        values: ['Torno', 'Soldadura', 'Otros']
                        size_hint_x: 0.3
                    TextInput:
                        id: operarios_3
                        input_filter: 'int'
                        size_hint_x: 0.1
                    TextInput:
                        id: cantidad_3
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: precio_3
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: porcentaje_3
                        input_filter: 'float'
                        size_hint_x: 0.1
                    TextInput:
                        id: total_mano_obra_3
                        readonly: True
                        size_hint_x: 0.2

                # Totales de Mano de Obra
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Total por Mano de Obra'
                        color: 1, 0, 0, 1  # Rojo
                        size_hint_x: 0.5
                    TextInput:
                        id: total_mano_obra_total
                        readonly: True
                        size_hint_x: 0.5

                # Partes Recibidas Torno/Soldadura
                LabelOscuro:
                    text: 'PARTES RECIBIDAS TORNO/SOLDADURA'
                    size_hint_y: None
                    height: '30sp'
                    font_size: 20
                    bold: True

                GridLayout:
                    cols: 2
                    size_hint_y: None
                    height: self.minimum_height
                    row_default_height: 30
                    padding: 10
                    spacing: 10

                    # Encabezados
                    Label:
                        text: 'PARTES RECIBIDAS'
                        color: 1, 1, 1, 1
                    Label:
                        text: 'CANT.'
                        color: 1, 1, 1, 1

                    # Filas dinámicas (ejemplo con 3 filas)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: partes_recibidas_1
                            size_hint_x: 0.8
                        TextInput:
                            id: cantidad_partes_1
                            input_filter: 'float'
                            size_hint_x: 0.2

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: partes_recibidas_2
                            size_hint_x: 0.8
                        TextInput:
                            id: cantidad_partes_2
                            input_filter: 'float'
                            size_hint_x: 0.2

                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        TextInput:
                            id: partes_recibidas_3
                            size_hint_x: 0.8
                        TextInput:
                            id: cantidad_partes_3
                            input_filter: 'float'
                            size_hint_x: 0.2

                # Totales
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'Sub-Total:'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.3
                    TextInput:
                        id: subtotal
                        readonly: True
                        size_hint_x: 0.7

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'IVA:'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.3
                    TextInput:
                        id: iva
                        readonly: True
                        size_hint_x: 0.7

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Label:
                        text: 'TOTAL+IVA:'
                        color: 1, 1, 1, 1
                        size_hint_x: 0.3
                    TextInput:
                        id: total_iva
                        readonly: True
                        size_hint_x: 0.7

                # Botones adicionales
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: 30
                    spacing: 10
                    Button:
                        text: 'Incluir Repuestos a esta Ficha'
                        on_release: root.incluir_repuestos()
                    Button:
                        text: 'Incluir Servicios Especiales'
                        on_release: root.incluir_servicios_especiales()
                    Button:
                        text: 'Imprimir Ficha Registrada'
                        on_release: root.imprimir_ficha()

        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 20
            BotonOscuro:
                text: 'Guardar'
                on_release: root.guardar_recepcion()
            BotonOscuro:
                text: 'Cancelar'
                on_release: root.dismiss()

            BotonOscuro:
                text: 'Agregar Fila'
                on_release: root.agregar_fila_mano_obra()




<SelectableInventarioLabel>:
    # Draw a background to indicate selection
    canvas.before:
        Color:
            rgba: hex('#C9F3EF') if self.selected else hex('#F0F0F0')
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
    	id: _idrepuesto
    	size_hint_x: .05
    	color: (0,0,0,1)
    Label:
    	id: _repuesto
    	size_hint_x: .25
    	color: (0,0,0,1)
    Label:
    	id: _grupo
    	size_hint_x: .2
    	color: (0,0,0,1)
    Label:
    	id: _unidad
    	size_hint_x: .2
    	color: (0,0,0,1)
    Label:
    	id: _existencia
    	size_hint_x: .1
    	color: (0,0,0,1)
    Label:
    	id: _costo
    	size_hint_x: .1
    	color: (0,0,0,1)
    Label:
    	id: _precio
    	size_hint_x: .1
    	color: (0,0,0,1)

<InventarioPopup>:
    size_hint: .7, .6  # Ajustado para mayor altura
    auto_dismiss: False
    title: 'Entrada Inventario'

    BoxLayout:
        orientation: 'vertical'
        padding: 15
        spacing: 8



        # Título - Altura fija
        Label:
            id: producto_info_1
            text: 'Agregar producto nuevo'
            bold: True
            color: (1, 1, 1, 1)
            halign: 'center'
            text_size: self.size
            size_hint_y: None  # ← Clave: desactivar size_hint_y
            height: 30        # ← Altura fija

        # Mensaje de error - Altura fija
        Label:
            id: no_valid_notif
            text: ''
            color: (1, 0, 0, 1)
            halign: 'center'
            text_size: self.size
            size_hint_y: None  # ← Clave
            height: 30        # ← Altura fija


        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            Label:
                text: 'Código:'
                size_hint_x: 0.3
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_codigo
                multiline: False
                write_tab: False

            Label:
                text: 'Nombre:'
                size_hint_x: 0.3
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_nombre
                multiline: False
                write_tab: False

            Label:
                text: 'Grupo:'
                size_hint_x: 0.3
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_grupo
                multiline: False
                write_tab: False


        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            Label:
                text: 'Unidad:'
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_unidad
                multiline: False
                write_tab: False

            Label:
                text: 'Existencia:'
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_existencia
                multiline: False
                input_filter: 'int'
                write_tab: False
            Label:
                text: 'Cantidad Mínima:'
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_minimo
                multiline: False
                write_tab: False
            Label:
                text: 'Cantidad Máxima:'
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_máximo
                multiline: False
                write_tab: False


        BoxLayout:
            size_hint_y: None
            height: 40
            spacing: 10
            Label:
                text: 'Costo:'
                size_hint_x: 0.3
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_costo
                size_hint_x: 0.7
                multiline: False
                input_filter: 'float'
                write_tab: False

            Label:
                text: 'Precio:'
                size_hint_x: 0.3
                color: (1, 1, 1, 1)
            TextInput:
                id: repuesto_precio
                size_hint_x: 0.7
                multiline: False
                input_filter: 'float'
                write_tab: False

        # Botones
        BoxLayout:
            size_hint_y: None
            height: 50
            spacing: 15

            Button:
                text: 'Aceptar'
                on_release: 
                    root.verificar(
                    repuesto_codigo.text, 
                    repuesto_nombre.text, 
                    repuesto_existencia.text, 
                    repuesto_precio.text
                    )

            Button:
                text: 'Cancelar'
                on_release: root.dismiss()





<VistaInventario>:
	name: 'Inventario'
	BoxLayout:
		BoxLayout:
			padding: .5
			orientation: 'vertical'
			BoxLayout:
				size_hint_y: .05
				spacing: .5
				LabelOscuro:
					text: 'Id'
					size_hint_x: .05
				LabelOscuro:
					text: 'Repuesto'
					size_hint_x: .25
				LabelOscuro:
					text: 'Grupo'
					size_hint_x: .20
				LabelOscuro:
					text: 'Unidad'
					size_hint_x: .20
				LabelOscuro:
					text: 'Existencia'
					size_hint_x: .1
				LabelOscuro:
					text: 'Costo'
					size_hint_x: .1
				LabelOscuro:
					text: 'Precio'
					size_hint_x: .1
			AdminRV:
				id: rv_productos
				size_hint_y: .89
				viewclass: 'SelectableInventarioLabel'
		BoxLayout:
			spacing: .5
			size_hint_x: .2
			orientation: 'vertical'
			padding: .5
			BotonOscuro:
				text: 'Agregar Producto'
				on_release: root.agregar_producto()
			BotonOscuro:
				text: 'Modificar Producto'
				on_release: root.modificar_producto()
			BotonOscuro:
				text: 'Eliminar Producto'
				on_release: root.eliminar_producto()
